modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/EvilCraft/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evilcraft"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="evilcraftcompat"
version="${file.jarVersion}"
displayName="EvilCraft-Compat"
description='''
EvilCraft compatibility with other mods.
'''
[[dependencies.evilcraftcompat]]
    modId="evilcraft"
    mandatory=true
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
