modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/EvilCraft/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evilcraft"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="evilcraftcompat"
version="${file.jarVersion}"
displayName="EvilCraft-Compat"
description='''
EvilCraft compatibility with other mods.
'''
[[dependencies.evilcraftcompat]]
    modId="evilcraft"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraftcompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
